# TEMPLATED
version: 2.1
workflows:
  version: 2
  build:
    jobs:
    - build-ente-staging:
        context: pip-staging
        filters:
          branches:
            only: /ente-staging.*/
    - build-ente-prod:
        context: production
        filters:
          branches:
            ignore: /ente-staging.*/
jobs:
  build_template: &build_template
    docker:
    - image: ${DOCKER_REGISTRY}/duckietown/aido-submission-ci-test:ente
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Install dts commands
        command: |
          pip install -U duckietown-shell
          dts --debug --set-version "$DTS_VERSION" exit
    - run:
        name: config
        command: |
          dts --debug challenges config \
            --docker-server "$DOCKER_REGISTRY" \
            --docker-username "$DOCKER_USERNAME" \
            --docker-password "$DOCKER_PASSWORD"

    - run:
        name: Python stats
        command: |
          mkdir -p build-stats
          env | sort | tee  build-stats/env.txt
          pip list   | sort | tee  build-stats/pip-list.txt
          pip freeze | sort | tee  build-stats/pip-freeze.txt

    - store_artifacts:
        path: build-stats
        destination: build-stats

    - run:
        name: Pull the image
        command: |
          dts devel pull --tag ente

    - run:
        name: Build the docs
        command: |
          dts devel docs build --tag ente -f

    - store_artifacts:
        path: html
        destination: html
    - run:
        name: Create a .tgz of  the folder `html` into html/package.tgz
        command: |
          # XXX: this a workaround for bugs in devel docs
          rm -f html/package.tgz
          tar -czf package.tgz -C html .
          mv package.tgz html/package.tgz
          tar tfz html/package.tgz
    - store_artifacts:
        path: html/package.tgz
        destination: out/package.tgz
  build-ente-prod: *build_template
  build-ente-staging: *build_template
